[Feature #161278920] added user notifications
andela/ah-sealteam pull request #43
Opened 2018-11-19 17:51 UTC by rickynyairo

### What does this PR do?

Creates the functionality for a user to receive email and app notifications

#### Description of Task to be completed?

- When activity happens in the application, the users who have subscribed to that activity receive notifications for the same

#### How should this be manually tested?
```
$ git fetch origin pull/40/head:ft-notifications-161278920
$ git checkout ft-notifications-161278920
$ python manage.py makemigrations
$ python manage.py migrate
$ python manage.py runserver
```
#### What are the relevant pivotal tracker stories?
[#161278920](https://www.pivotaltracker.com/n/projects/2205273/stories/161278920)

2018-11-20 11:14 UTC, susanwere approved these changes

2018-11-20 14:00 UTC, botnetdobbs approved these changes

2018-11-22 09:35 UTC, asheux approved these changes

2018-11-27 07:16 UTC, Adoniswalker requested changes
Hi Ricky, I can see a lot of quality work you have done. I run into the following problem when reviewing your PR.

1. When trying to post an Article and I have a follower 
gaierror at /api/articles/
[Errno 8] nodename nor servname provided, or not known
2. When tying to mark all notifications as read.
KeyError at /api/notifications/read/
'pk' PUT
3. marking all notifications as unread not working both POST and PUT, they are not allowed methods

4. When i try to use other methods during subscription and unsubscribing
Try to get AssertionError at /api/notifications/subscribe/
'SubscribeAPIView' should either include a `queryset` attribute, or override the `get_queryset()` method. I should get METHOD get not allowed

5. TypeError at /api/notifications/unsubscribe/
get() missing 1 required positional argument: 'token' when i try get

2018-11-28 07:17 UTC, gtsofa approved these changes

2018-12-03 10:01 UTC, rickynyairo commented
@Adoniswalker 
For the email unsubscription, click the link in the email that is sent with the notification email.  
The other changes have been handled. Please review

2018-12-03 12:30 UTC, Adoniswalker approved these changes

2018-12-04 08:20 UTC, merged